### PR TITLE
refactor: remove deprecated html-attributes library

### PR DESCRIPTION
**Pull request by dazedbear**
## Goal

Hi team, I noticed one of your dependencies, `html-attributes`, has been stale for more than five years, and its repo even was deleted. 

- https://www.npmjs.com/package/html-attributes
- https://github.com/alexmingoia/html-attributes

Thus, I create this PR to copy the HTML attributes mapping from that package to remove this dependency.

**Source code reference**

screencapture-npmjs-package-html-attributes-2022-12-22-11_33_29

### CODE REVIEW

**Comment by ismailshak** [comment]
thanks for the contribution!

we're gonna have to sort out some publishing issues before we can merge this. in the meantime, could you rebase your current branch with latest on `main` (`master` was renamed)? just so that we can remove that dependency from the lockfile too

**Comment by dazedbear** [comment]
@ismailshak I've rebased my PR. Could you review it again once you fix the publishing issue? Thanks.

**Comment by dazedbear** [comment]
@ismailshak @AndrewCsontos This PR has been rebased. Could you take a look, please?

**Comment by ismailshak** [comment]
@dazedbear LGTM. We want to publish the current head under `v3.0.0` before we merge and publish this change. We're currently working on getting publishing rights fixed, hopefully resolved next week when life resumes post-holidays. So until then, we'll keep this in a PR. I'll approve, merge and publish this as soon as everything's back in order. Thank you for your patience!

**Comment by dazedbear** [comment]
Hi @ismailshak, is there any good luck on the publish fix?

**Comment by ismailshak** [comment]
Hi @dazedbear, unfortunately not yet. We're still working on it & we'll address this PR as soon as we can publish again. Thanks

**Comment by dazedbear** [comment]
Hi @ismailshak, any good luck on this? If not, shall we stop here and close this PR?

**Comment by ismailshak** [comment]
@dazedbear appreciate your patience on this one. We've managed to acquire the correct permissions, so I'll release your change now

**Review by ismailshak — APPROVED** [review]

**Comment by ismailshak** [comment]
https://github.com/socialtables/filter-invalid-dom-props/releases/tag/v3.0.1

**Pull request merged**
